

export enum pagePermission {
    WORK_GET= 'PAGE_WORK_GET',
    WROK_POST='PAGE_WORK_POST',
    MEETING_APPROVAL='PAGE_MEETING_APPROVAL',
    TRANSACTION_APPROVAL='PAGE_TRANSACTION_APPROVAL',
    SUPERVISE_CREATE='PAGE_SUPERVISE_CREATE',
    office = 'office',
    LEADER_SCHEDULE = 'LEADER_SCHEDULE',
    supervise='supervise',
    MEETINGROOM_MANAGE = 'MEETINGROOM_MANAGE'
}


export enum btnPermission {
    ANNOUNCEMENT_INSERT = 'ANNOUNCEMENT_INSERT',
    ANNOUNCEMENT_DELETE = 'ANNOUNCEMENT_DELETE',
    ANNOUNCEMENT_UPDATE = 'ANNOUNCEMENT_UPDATE',
    MEETINGROOM_INSERT='MEETINGROOM_INSERT',
    MEETINGROOM_DELETE='MEETINGROOM_DELETE',
    MEETINGROOM_UPDATE='MEETINGROOM_UPDATE',
    SCORE_INSERT='SCORE_INSERT',
    SCORE_DELETE='SCORE_DELETE',
    SCORE_UPDATE='SCORE_UPDATE',

}